"""
git post-commit hook のインストールスクリプト。
faq_master.json または glossary_master.json が変更されたコミット時に
自動で Excel エクスポートを実行する。

Usage:
    python scripts/install_hooks.py
"""
import sys
import io
from pathlib import Path

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

HOOK_CONTENT = r"""#!/bin/sh
# Auto-generated by scripts/install_hooks.py
# faq_master.json または glossary_master.json の変更を検知してExcelを自動エクスポート

CHANGED=$(git diff-tree --no-commit-id -r --name-only HEAD)

echo "$CHANGED" | grep -qE "(faq_master\.json|glossary_master\.json)" || exit 0

echo "[post-commit] ナレッジ更新を検知 → Excel エクスポート中..."
python scripts/export_to_excel.py
if [ $? -eq 0 ]; then
    echo "[post-commit] Excel エクスポート完了"
else
    echo "[post-commit] Excel エクスポート失敗（コミット自体は成功しています）"
fi
"""

def main():
    repo_root = Path(__file__).parent.parent
    hook_path = repo_root / ".git" / "hooks" / "post-commit"

    hook_path.write_text(HOOK_CONTENT, encoding="utf-8")

    # Windows でも実行可能にする（Unix パーミッション）
    import stat
    hook_path.chmod(hook_path.stat().st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)

    print(f"[OK] post-commit hook をインストールしました: {hook_path}")
    print("     faq_master.json / glossary_master.json の変更コミット時に自動でExcelを生成します")
    print(f"     出力先: {repo_root / 'data' / 'excel' / 'srcc_knowledge_YYYYMMDD_HHMMSS.xlsx'}")


if __name__ == "__main__":
    main()
